# Generated by Django 5.2.9 on 2025-12-07 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, help_text='Last 4 digits only for security', max_length=100)),
                ('institution_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('investment', 'Investment Account'), ('retirement', 'Retirement Account (401k, IRA)'), ('credit_card', 'Credit Card'), ('loan', 'Loan Account'), ('mortgage', 'Mortgage'), ('real_estate', 'Real Estate'), ('business', 'Business Account'), ('other', 'Other')], max_length=20)),
                ('ownership', models.CharField(choices=[('joint', 'Joint'), ('petitioner', 'Petitioner Only'), ('respondent', 'Respondent Only'), ('business', 'Business Entity')], default='joint', max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_reconciled_date', models.DateField(blank=True, null=True)),
                ('plaid_account_id', models.CharField(blank=True, max_length=255)),
                ('external_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'db_table': 'financial_accounts',
                'ordering': ['institution_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('separate_property_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('marital_property_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_dip_point', models.BooleanField(default=False, help_text='True if this is a lowest intermediate balance point')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='finance.financialaccount')),
            ],
            options={
                'verbose_name': 'Balance Snapshot',
                'verbose_name_plural': 'Balance Snapshots',
                'db_table': 'balance_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SeparatePropertyClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('inheritance', 'Inheritance'), ('gift', 'Gift'), ('premarital', 'Pre-marital Asset'), ('personal_injury', 'Personal Injury Settlement'), ('trust', 'Trust Distribution'), ('other', 'Other')], max_length=20)),
                ('initial_deposit_date', models.DateField(db_index=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('current_traceable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount traceable under LIBR', max_digits=15)),
                ('lowest_balance_date', models.DateField(blank=True, help_text='Date when account hit lowest intermediate balance', null=True)),
                ('lowest_balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_status', models.CharField(choices=[('pending', 'Pending Calculation'), ('calculating', 'Calculating'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separate_property_claims', to='finance.financialaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separate_claims', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_documentation', models.ManyToManyField(blank=True, related_name='separate_property_claims', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Separate Property Claim',
                'verbose_name_plural': 'Separate Property Claims',
                'db_table': 'separate_property_claims',
                'ordering': ['-initial_deposit_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('post_date', models.DateField(blank=True, help_text='Date transaction posted to account', null=True)),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for deposits, negative for withdrawals', max_digits=15)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('interest', 'Interest'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], default='withdrawal', max_length=20)),
                ('category', models.CharField(choices=[('income_salary', 'Salary/Wages'), ('income_business', 'Business Income'), ('income_investment', 'Investment Income'), ('income_other', 'Other Income'), ('expense_housing', 'Housing'), ('expense_utilities', 'Utilities'), ('expense_food', 'Food/Groceries'), ('expense_transportation', 'Transportation'), ('expense_healthcare', 'Healthcare'), ('expense_childcare', 'Childcare'), ('expense_education', 'Education'), ('expense_entertainment', 'Entertainment'), ('expense_personal', 'Personal'), ('expense_business', 'Business Expense'), ('expense_legal', 'Legal Fees'), ('transfer', 'Transfer'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=30)),
                ('memo', models.TextField(blank=True)),
                ('check_number', models.CharField(blank=True, max_length=20)),
                ('is_separate_property', models.BooleanField(default=False, help_text='Mark as separate property deposit')),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Account balance after this transaction', max_digits=15, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cases.case')),
                ('separate_property_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transactions', to='finance.separatepropertyclaim')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['case', '-updated_at'], name='financial_a_case_id_285182_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type'], name='financial_a_account_a2a171_idx'),
        ),
        migrations.AddIndex(
            model_name='balancesnapshot',
            index=models.Index(fields=['account', '-snapshot_date'], name='balance_sna_account_99ef63_idx'),
        ),
        migrations.AddIndex(
            model_name='balancesnapshot',
            index=models.Index(fields=['case', '-snapshot_date'], name='balance_sna_case_id_09a55c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesnapshot',
            unique_together={('account', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='separatepropertyclaim',
            index=models.Index(fields=['case', '-initial_deposit_date'], name='separate_pr_case_id_92c223_idx'),
        ),
        migrations.AddIndex(
            model_name='separatepropertyclaim',
            index=models.Index(fields=['account', '-initial_deposit_date'], name='separate_pr_account_7da36b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['case', '-transaction_date'], name='transaction_case_id_124871_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-transaction_date'], name='transaction_account_ea5d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'external_id')},
        ),
    ]
