# Generated by Django 5.2.9 on 2025-12-07 04:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, help_text='Court case number or internal reference', max_length=50, unique=True)),
                ('case_title', models.CharField(help_text='e.g., "Smith v. Smith"', max_length=255)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('court_jurisdiction', models.CharField(blank=True, max_length=100)),
                ('judge_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('discovery', 'Discovery'), ('negotiation', 'Negotiation'), ('litigation', 'Litigation'), ('settlement', 'Settlement'), ('closed', 'Closed'), ('archived', 'Archived')], default='initiated', max_length=20)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('separation_date', models.DateField(blank=True, help_text='Date of separation - critical for financial tracing', null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('expected_resolution_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('estimated_marital_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_separate_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Note'), ('financial', 'Financial Observation'), ('legal', 'Legal Strategy'), ('communication', 'Communication Log'), ('evidence', 'Evidence Note'), ('deadline', 'Deadline/Reminder')], default='general', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='Private notes only visible to creator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Note',
                'verbose_name_plural': 'Case Notes',
                'db_table': 'case_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('petitioner', 'Petitioner'), ('respondent', 'Respondent'), ('attorney_petitioner', 'Attorney for Petitioner'), ('attorney_respondent', 'Attorney for Respondent'), ('mediator', 'Mediator'), ('financial_expert', 'Financial Expert'), ('observer', 'Observer')], max_length=30)),
                ('can_view_financials', models.BooleanField(default=True)),
                ('can_edit_financials', models.BooleanField(default=False)),
                ('can_view_communications', models.BooleanField(default=True)),
                ('can_send_communications', models.BooleanField(default=True)),
                ('can_view_evidence', models.BooleanField(default=True)),
                ('can_upload_evidence', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Party',
                'verbose_name_plural': 'Case Parties',
                'db_table': 'case_parties',
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('marriage', 'Marriage'), ('separation', 'Separation'), ('filing', 'Court Filing'), ('financial', 'Financial Event'), ('custody', 'Custody Event'), ('property', 'Property Event'), ('communication', 'Communication'), ('legal', 'Legal Proceeding'), ('other', 'Other')], max_length=20)),
                ('is_key_event', models.BooleanField(default=False, help_text='Mark as key event for case summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'case_timeline',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
