# Generated by Django 5.2.9 on 2025-12-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetimeline',
            name='related_evidence',
            field=models.ManyToManyField(blank=True, related_name='timeline_events', to='evidence.evidencedocument'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-created_at'], name='cases_status_3d2163_idx'),
        ),
        migrations.AddIndex(
            model_name='casenote',
            index=models.Index(fields=['case', '-created_at'], name='case_notes_case_id_6103ed_idx'),
        ),
        migrations.AddIndex(
            model_name='casenote',
            index=models.Index(fields=['category', '-created_at'], name='case_notes_categor_c1603c_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['case', 'role'], name='case_partie_case_id_450448_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['user', '-joined_at'], name='case_partie_user_id_159303_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparty',
            unique_together={('case', 'user')},
        ),
        migrations.AddIndex(
            model_name='casetimeline',
            index=models.Index(fields=['case', '-event_date'], name='case_timeli_case_id_e6bdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='casetimeline',
            index=models.Index(fields=['event_type', '-event_date'], name='case_timeli_event_t_1c58a1_idx'),
        ),
    ]
