# Generated by Django 5.2.9 on 2025-12-07 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('original_body', models.TextField(help_text='Original message before BIFF filtering')),
                ('processed_body', models.TextField(blank=True, help_text='BIFF-filtered message text')),
                ('was_filtered', models.BooleanField(default=False)),
                ('ai_filter_applied', models.BooleanField(default=False)),
                ('ai_filter_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ai_filter_notes', models.TextField(blank=True)),
                ('toxicity_score', models.FloatField(blank=True, null=True)),
                ('flagged_as_hostile', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='messages', to='evidence.evidencedocument')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communication.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='communication.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BIFFAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_score', models.IntegerField()),
                ('informative_score', models.IntegerField()),
                ('friendly_score', models.IntegerField()),
                ('firm_score', models.IntegerField()),
                ('overall_score', models.FloatField()),
                ('is_compliant', models.BooleanField()),
                ('issues_found', models.JSONField(default=list)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biff_analysis', to='communication.message')),
            ],
            options={
                'verbose_name': 'BIFF Analysis',
                'verbose_name_plural': 'BIFF Analyses',
                'db_table': 'biff_analyses',
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='communication.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_recipients',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='communication.MessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('pickup_dropoff', 'Pickup/Dropoff Schedule'), ('expense_request', 'Expense Request'), ('schedule_change', 'Schedule Change Request'), ('information_request', 'Information Request'), ('document_sharing', 'Document Sharing'), ('general', 'General Communication')], max_length=30)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField(help_text='Use {variables} for dynamic content')),
                ('available_variables', models.JSONField(default=list, help_text='List of allowed variables in this template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'message_templates',
                'ordering': ['template_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('platform', 'Platform Message'), ('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message'), ('in_person', 'In Person'), ('other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('assessed_tone', models.CharField(blank=True, choices=[('professional', 'Professional'), ('neutral', 'Neutral'), ('tense', 'Tense'), ('hostile', 'Hostile'), ('cooperative', 'Cooperative')], max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_logs', to='cases.case')),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_sent', to='cases.caseparty')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_received', to='cases.caseparty')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.message')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'db_table': 'communication_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['case', 'timestamp'], name='communicati_case_id_a7b3a1_idx'), models.Index(fields=['from_party', 'timestamp'], name='communicati_from_pa_d67f19_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['recipient', 'message'], name='message_rec_recipie_7e202d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['case', 'sent_at'], name='messages_case_id_a549db_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'sent_at'], name='messages_sender__039ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_root', 'sent_at'], name='messages_thread__272216_idx'),
        ),
    ]
