# Generated by Django 5.2.9 on 2025-12-07 04:42

import django.core.validators
import django.db.models.deletion
import evidence.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=evidence.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'csv'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=127)),
                ('file_hash_sha256', models.CharField(db_index=True, help_text='SHA-256 hash for integrity verification', max_length=64, unique=True)),
                ('file_hash_md5', models.CharField(blank=True, help_text='MD5 hash for compatibility with legacy systems', max_length=32)),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('tax_return', 'Tax Return'), ('pay_stub', 'Pay Stub'), ('property_deed', 'Property Deed'), ('appraisal', 'Appraisal'), ('invoice', 'Invoice/Receipt'), ('contract', 'Contract'), ('correspondence', 'Correspondence'), ('court_filing', 'Court Filing'), ('photo', 'Photograph'), ('other', 'Other Document')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, help_text='Date the document was created/dated', null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted via OCR')),
                ('ocr_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR confidence score 0-1', null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('blockchain_timestamp', models.JSONField(blank=True, help_text='OpenTimestamps or similar proof', null=True)),
                ('is_privileged', models.BooleanField(default=False, help_text='Attorney work product or privileged communication')),
                ('is_redacted', models.BooleanField(default=False, help_text='Contains redacted information')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags for document organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Document',
                'verbose_name_plural': 'Evidence Documents',
                'db_table': 'evidence_documents',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exhibit_prefix', models.CharField(blank=True, help_text='E.g., "PX" for Petitioner Exhibit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_collections', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='collections', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Evidence Collection',
                'verbose_name_plural': 'Evidence Collections',
                'db_table': 'evidence_collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('modify', 'Modified'), ('delete', 'Deleted'), ('share', 'Shared')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Evidence Access Log',
                'verbose_name_plural': 'Evidence Access Logs',
                'db_table': 'evidence_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('version_file', models.FileField(upload_to='evidence/versions/')),
                ('version_hash_sha256', models.CharField(max_length=64)),
                ('change_description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Evidence Version',
                'verbose_name_plural': 'Evidence Versions',
                'db_table': 'evidence_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['case', '-upload_timestamp'], name='evidence_do_case_id_fa1f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['document_type', '-document_date'], name='evidence_do_documen_5b0e87_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['file_hash_sha256'], name='evidence_do_file_ha_9e030c_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceaccesslog',
            index=models.Index(fields=['document', '-timestamp'], name='evidence_ac_documen_6c6cca_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceaccesslog',
            index=models.Index(fields=['user', '-timestamp'], name='evidence_ac_user_id_0c3191_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidenceversion',
            unique_together={('original_document', 'version_number')},
        ),
    ]
